services:
  - type: web
    name: fastapi-app
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install poetry && poetry config virtualenvs.create false && poetry install --no-dev
    startCommand: poetry run python -m ga_api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString

databases:
  - name: fastapi-db
    plan: starter
    region: oregon
